dist: trusty
language: java
jdk:
- oraclejdk8
sudo: false
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
install: true
script: "./gradlew clean build coveralls"
deploy:
- provider: script
  script: "./gradlew binTrayUpload"
  on:
    tags: true
  skip_cleanup: true
- provider: script
  script: "./gradlew publishPlugins -p restdocs-api-spec-gradle-plugin"
  on:
    tags: true
  skip_cleanup: true
env:
  global:
  - CI_NAME=travis-ci
  - secure: nOkY2AcR5Z7hKKzi+zCzmzPk+xiRRrJjGliDJnHnEO7g+iJ8SmT+thHuMFcXqvjxJ006LbR3GPB8M8qgFXFDPEUDRPppShi3waOm1ddlM2iXh9kbCoROoioyRO+F07deH6ExibkLbu/xq3WwAAw7lx/ZP+buc2R2VCbV0nLKP9iE4nHQX8msLgmU1LjWf0Au1Pgl2eWXV0J4/ZJOvcVu9hvBf1Ow4C7BNb0KZmMjeT9uMK0hiGpb9VVbwedOWfsbaFmqmKYqVKS8UtNmG+HBjvZfajrIARKRPc9w9uEvfl4E1H/J7PJLy2kOrCOauj8LMu6DduSrWcg08T5VnH51cavSAsWWG1ImTgEsUBNpllc9r1XLhQCLQ1TWCgGmleqYjZ2ySvg0MQpFjTgXMZC+aDkjZjcEeq3BgrncAR/bcG4ByrZBWyoEXDxBwoMZnkryTxK07UUgXRXdjJUldJ5CQW9oSfd+oEXKJyqQGNt0ob3S0sRS5uhrKniK+6Mwzxf6vXeYvn2fVP5j3hocUz4XzDJQoDDmJi6D4BpwksqJ81CNOHpyeDIOhdXxvA/J8DMCK0Q7tTSbnSOxItaht56CSxqqLSGax3/4Nr+5QX9jpmdJ03HdpP+MOuIl6dZCmE4/w1IFaFEfhpETPlnWZHl1BsOt7omDeW7yCttDq3Y1mXU=
  - secure: 4DTaXQyT0oj4GkmDYRT0goQ7B/wGAjLov9xRssyz7aEKZaZZS/y4YSZ7LEI57dZYLkwtekiR1zN6gLnB6XGTMh2MVRGZ1vzcwsR1HebyjFHf5+2YHXRKq/mJk4K4q6t9GtXKZYz3yDnXtn7S2NgkIhye0E1t2874kEPcIEhKClLIGKjCsVenx1ui4WxBMVFPyhAe5KKn73HFTZORzPtTzoYDM9akhZm+Ko0ObreJZdy/P9pHU+RGQjPFWRbjNlrBg1uiBhYOWPGXrOwKMxNnl2fNUilF0QHaDt0oYbeBJvXKgqqC90Qrb067+ynL5S567uesY16A0MtYDIYiDAt0ytSH4B5fjWpFR5WWU+X9uPTAzP4HTwNYfdOBnvtUrRUlYNdxWxwS7ZOzoMFKt7UHs/42VoJBURBBhP7g6qFIJb+OtdDk6iSpqsa/VSMaB59HsKkitB2ZDh7ohmWBu0wZ1iIN6hEYd94/HFWv4C6Fkntbxgv+kVETVNmeA6yLMvLF46Jg8a1s2XptCUFb5kQpgaitbEPnso8lAwXCPRQlj064Ctym8oPCi4hYZcWHm4sF1RYFVweVaa1+5wQI5go6dTgrQajYwRJU0WmtmYfb9pr/l5NeAk2tuYEnX/ILs6TB1by5qJUQzCnaF7YgERrG84t4lqByBGdZaIiFMRIVXCw=
  - secure: iEfnO6ZvdyY2Sx0uDafjRgyqPsUueEZtvWumhSRQCBEpQ6MDQiWQTX3SGYtgdX61eShiqwVo3bnp3eeCCojUCtXHFM+sE+bk3NOMuocq4p1Q6uZrt1oe7nK8wYBPdl+5iema1UtSiYiAw6FGlAnDsDjvBkIa7vGpoGyToa68hzLjwNWMi6Jz9JPEoCwIIKSZn8J8gYbeKr1CMLkwpLZYfsh077mXRC22yH0jh7c6kQSfdUuW7a6fELQiQXgccp8qR11oJ5AI17prFa+4q09xCk4pbrhCHMXRrOHDfRLicXWN3qgF8rqETLLRGM1LPpwsgkoFqBEs93RT+3USpWs2H8sC5LgG3m76QP4stRekEmmlJJnIT9ohTt6SAWvrszoYYusTfJbVwQewKXQppshcUIubL7GqaJ0gaTgU7O3tX2o7lTi0dw27FcXV2KpSBSkNok1AZy9iWhGoeSWupi8APe37IwUHjPTiu3on07hbuRXQ/7qvVxujftwiDR3Tbb5AoG3tvtr5+Ru58Ie4PyhxuP1AYbUkgWxVx2MOBHeePHm59wfXIytKoSAGIi0uFwlCqBV926sJCbKwv0c2Kh5SkJvA/1TNTFYITgiiIL9DyxziXUzvsJAkO2ZyA8FLCpMM+WqMnB/M5jxrFzqFFfvhP5dSZSd3OkUO2bhHJuCS2BU=
  - secure: XZ4MKhQkOcOp7iRpq/DPJu4RkGs6+26ykgo1n+NZDJlamJ+hikW0JahBuJdi30z/JVnXcpbHkVfmUSrHyWg0irggtOB+E566pRw/iPzeH6ZRzs0gFYdWujPv7BTXDZzzfGck8gSnMFDStHK1MYOYNYc8T1hNytwPy4WygGwc8mcgdbda5TTJuI0gbNm+5gehjW+h5tjeR6UrUBSj2Gbx+/UdJ3oXPOHFFu0i4OuXTSkWZz7Dz1M7o9loJOUtHwKB5osm9+tUQqLiI9yRE4Z80ngOC8eoF7HqBKFydoezqE+DCxNg+Vy+RkkTpa+mvBD+k5bZ/7BeFmOQdzE61YM1/xN1CaAjjFEI0KEisZ3gycdnxUp7sLkBuCMPfuhix3Sqjt9ulEv4k1MRMsXBJ7Wpe+ZuovHuXFlu1ni6tU5pRs5BhCnXc+X7dDvaprJUbB1pSp6/Rjpf5nOIszVf/HkO6MmgMQkZLwlcu6I8QPnOCfkW8FJroyOTUr/MD/oPNVGRLvANZuyqqNtEc9g/Nt6f0qSvlkdEOVcgBlz95d8UbkhEYbYbB71gqOo+flhfgIDOWEXgkrGjY7p95g5R+VIKSBaXv36EYyNPVAQQ55riyPnDpU5JUnur6GZIY+jTuNS0Tp6tXhPksRcBNjKEUqfte8YqI8EvdZfzvloODsb+9Wk=
  - secure: nd2+OblPYu7qdG0D/lkbKMhoxaEm/U/IWQQ7HJYK5Yjt6f/JOgux0OIA/m+OO/3wtWDTbT+ihRekIcIU/x3ab4b1P1cwP1pMDsqc8O3Nqa8K79AGOYx5c3vZ7M5DBiLYKZDSM7VAaz0ol1uoY7Lo0jCMJQsf74U4o2xunrok5bf511cAJZ4gcczZ3hfoTu98gonil71Ln9TrdE9f86dX/aI7hmD9dajjxz98JkQSR/Cf47W4oAbBla85rHlDdzzrnGuVyhpV3r1ib2lrpcrBHID5IhSXyCEJxdbCNAlTCGuXdBMG+m99h9hYw7Nq1OsxbO2gmqs77fXmwKpPGwtf5PLGlQdkcExsdvNORmTeIn5Ac8JNDiEz8w/jrpBqkVZ5x6yVeSUe5VqAR1GLCrqIud2W3dDefWsSEhHtvu/iJYPB8IN01S55V7Uzy7hfs4Z6DnjPxT5khRleUViQywhFZ4/+yQ5OELeLbrGaDwZuZI2WOMahvgV749NrdCZ6SeIZSptr6ywCH7OFUJIbgiYvv0wxgpqg3cYeQ5OsUFR/+dWkXA+rk+17N7PodCAHl9Cg1ckg1N5H2AYAQzxn8mSELb2STRZpViygbiDeadrjnJBr8kFYdWkFc4fTX2CeboD7MitUjOWXvvQrlyU+R9BVaxs1cV8iTCLnP1dt0HKXKBA=
